import { awscdk, javascript } from "projen";
const project = new awscdk.AwsCdkConstructLibrary({
  eslint: true,
  author: "Dany Alawwa",
  authorAddress: "dalawwa@gmail.com",
  cdkVersion: "2.1.0",
  defaultReleaseBranch: "main",
  jsiiVersion: "~5.0.0",
  name: "appsync-transformer",
  packageManager: javascript.NodePackageManager.YARN2,
  gitignore: [
    "appsync/*",
    "customtest/*",
    ".pnp.*",
    ".yarn/*",
    ".yarn/cache",
    "!.yarn/patches",
    "!.yarn/plugins",
    "!.yarn/releases",
    "!.yarn/sdks",
    "!.yarn/versions",
  ],
  npmignore: [
    "appsync/*",
    "customtest/*",
    ".pnp.*",
    ".yarn/*",
    ".yarn/cache",
    "!.yarn/patches",
    "!.yarn/plugins",
    "!.yarn/releases",
    "!.yarn/sdks",
    "!.yarn/versions",
  ],
  projenrcTs: true,
  repositoryUrl: "https://github.com/dany.alawwa/testProjen.git",
  typescriptVersion: "^5.2.0",
  tsconfig: {
    compilerOptions: {
      lib: ["es2022"],
      alwaysStrict: true,
      declaration: true,
      esModuleInterop: true,
      experimentalDecorators: true,
      inlineSourceMap: true,
      inlineSources: true,
      noEmitOnError: false,
      noFallthroughCasesInSwitch: true,
      noImplicitAny: true,
      noImplicitReturns: true,
      noImplicitThis: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      resolveJsonModule: true,
      strict: true,
      strictNullChecks: true,
      strictPropertyInitialization: true,
      stripInternal: true,
      target: "es2022",
    },
  },
  bundledDeps: ["graphql-transformer-core"],
  deps: [
    "aws-cdk-lib",
    "graphql-transformer-core",
    "graphql@^15.5.0",
    "graphql-auth-transformer",
    "graphql-connection-transformer",
    "graphql-dynamodb-transformer",
    "graphql-function-transformer",
    "graphql-http-transformer",
    "graphql-key-transformer",
    "graphql-mapping-template",
    "graphql-relational-schema-transformer",
    "graphql-transformer-common",
    "graphql-versioned-transformer",
    "@aws-amplify/amplify-cli-core",
    "@aws-amplify/graphql-transformer-interfaces",
    "cloudform-types",
  ] /* Runtime dependencies of this module. */,
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  devDeps: [
    "@typescript-eslint/eslint-plugin",
    "@typescript-eslint/parser",
    "eslint",
  ] /* Build dependencies for this module. */,
  // packageName: undefined,  /* The "name" in package.json. */
});

// project.eslint?.overrides.push({
//   files: ["custom-vtl-transformer.ts"],
//   rules: {
//     "import/no-extraneous-dependencies": "off",
//   },
// });
project.synth();
